default: &default
  database: every_world_city
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  username: everycityapp
  password: c9e8f54f7d77aed76e45b836e41acee5
  host: localhost
